"""
Script to generate sample blood test PDFs for testing GutCheck.
Run this to create the 3 sample reports mentioned in the PRD.
"""

import fitz  # PyMuPDF


def create_healthy_report():
    """Create healthy_25f.pdf - All normal biomarkers."""
    
    content = """
BLOOD TEST REPORT
=================

Patient Information:
Name: Jane Smith
Age: 25
Sex: Female
Date: February 15, 2026

LABORATORY RESULTS
------------------

COMPLETE BLOOD COUNT (CBC)

Hemoglobin              13.8 g/dL     (Normal: 12.0-16.0)
Hematocrit              41.0 %        (Normal: 37-47)
Red Blood Cell Count    4.5 M/uL      (Normal: 3.8-5.2)
White Blood Cell Count  7,200 /uL     (Normal: 4,500-11,000)
Platelet Count          250,000 /uL   (Normal: 150,000-450,000)

METABOLIC PANEL

Blood Sugar (Glucose)   88 mg/dL      (Normal: 70-100)
Cholesterol, Total      175 mg/dL     (Normal: <200)
HDL Cholesterol         65 mg/dL      (Normal: >50)
LDL Cholesterol         95 mg/dL      (Normal: <100)
Triglycerides           75 mg/dL      (Normal: <150)

VITAMINS & MINERALS

Vitamin D               42 ng/mL      (Normal: 30-100)
Iron                    95 mcg/dL     (Normal: 60-170)
Ferritin                45 ng/mL      (Normal: 12-150)
Vitamin B12             450 pg/mL     (Normal: 200-900)

LIVER FUNCTION

ALT                     22 U/L        (Normal: 7-56)
AST                     20 U/L        (Normal: 10-40)
Albumin                 4.2 g/dL      (Normal: 3.5-5.5)

KIDNEY FUNCTION

Creatinine              0.9 mg/dL     (Normal: 0.6-1.2)
BUN                     14 mg/dL      (Normal: 7-20)

---
Report generated by GutCheck Lab Systems
"""
    
    doc = fitz.open()
    page = doc.new_page()
    
    # Insert text
    text_point = fitz.Point(50, 50)
    page.insert_text(text_point, content, fontsize=11, fontname="helv")
    
    doc.save("sample_reports/healthy_25f.pdf")
    doc.close()
    print("Created: sample_reports/healthy_25f.pdf")


def create_deficient_report():
    """Create deficient_40m.pdf - Multiple deficiencies (YELLOW status)."""
    
    content = """
BLOOD TEST REPORT
=================

Patient Information:
Name: John Doe
Age: 40
Sex: Male
Date: February 20, 2026

LABORATORY RESULTS
------------------

COMPLETE BLOOD COUNT (CBC)

Hemoglobin              11.2 g/dL     (Normal: 13.5-17.5) *** LOW ***
Hematocrit              35.0 %        (Normal: 41-50) *** LOW ***
Red Blood Cell Count    3.9 M/uL      (Normal: 4.5-5.9) *** LOW ***
White Blood Cell Count  6,800 /uL     (Normal: 4,500-11,000)
Platelet Count          220,000 /uL   (Normal: 150,000-450,000)

METABOLIC PANEL

Blood Sugar (Glucose)   95 mg/dL      (Normal: 70-100)
Cholesterol, Total      215 mg/dL     (Normal: <200) *** HIGH ***
HDL Cholesterol         42 mg/dL      (Normal: >40)
LDL Cholesterol         145 mg/dL     (Normal: <100) *** HIGH ***
Triglycerides           140 mg/dL     (Normal: <150)

VITAMINS & MINERALS

Vitamin D               18 ng/mL      (Normal: 30-100) *** LOW ***
Iron                    45 mcg/dL     (Normal: 60-170) *** LOW ***
Ferritin                22 ng/mL      (Normal: 24-336) *** LOW ***
Vitamin B12             380 pg/mL     (Normal: 200-900)

LIVER FUNCTION

ALT                     35 U/L        (Normal: 7-56)
AST                     32 U/L        (Normal: 10-40)
Albumin                 4.0 g/dL      (Normal: 3.5-5.5)

KIDNEY FUNCTION

Creatinine              1.1 mg/dL     (Normal: 0.7-1.3)
BUN                     16 mg/dL      (Normal: 7-20)

---
*** FLAGGED VALUES REQUIRE ATTENTION ***

Report generated by GutCheck Lab Systems
"""
    
    doc = fitz.open()
    page = doc.new_page()
    
    text_point = fitz.Point(50, 50)
    page.insert_text(text_point, content, fontsize=11, fontname="helv")
    
    doc.save("sample_reports/deficient_40m.pdf")
    doc.close()
    print("Created: sample_reports/deficient_40m.pdf")


def create_risk_report():
    """Create risk_55m.pdf - Multiple urgent concerns (RED status)."""
    
    content = """
BLOOD TEST REPORT
=================

Patient Information:
Name: Robert Chen
Age: 55
Sex: Male
Date: February 22, 2026

LABORATORY RESULTS
------------------

COMPLETE BLOOD COUNT (CBC)

Hemoglobin              10.1 g/dL     (Normal: 13.5-17.5) *** VERY LOW ***
Hematocrit              31.0 %        (Normal: 41-50) *** VERY LOW ***
Red Blood Cell Count    3.4 M/uL      (Normal: 4.5-5.9) *** LOW ***
White Blood Cell Count  5,200 /uL     (Normal: 4,500-11,000)
Platelet Count          180,000 /uL   (Normal: 150,000-450,000)

METABOLIC PANEL

Blood Sugar (Glucose)   126 mg/dL     (Normal: 70-100) *** HIGH - PRE-DIABETIC ***
Cholesterol, Total      268 mg/dL     (Normal: <200) *** HIGH ***
HDL Cholesterol         35 mg/dL      (Normal: >40) *** LOW ***
LDL Cholesterol         185 mg/dL     (Normal: <100) *** VERY HIGH ***
Triglycerides           210 mg/dL     (Normal: <150) *** HIGH ***

VITAMINS & MINERALS

Vitamin D               12 ng/mL      (Normal: 30-100) *** CRITICALLY LOW ***
Iron                    38 mcg/dL     (Normal: 60-170) *** LOW ***
Ferritin                18 ng/mL      (Normal: 24-336) *** LOW ***
Vitamin B12             290 pg/mL     (Normal: 200-900)

LIVER FUNCTION

ALT                     48 U/L        (Normal: 7-56)
AST                     45 U/L        (Normal: 10-40)
Albumin                 3.8 g/dL      (Normal: 3.5-5.5)

KIDNEY FUNCTION

Creatinine              1.3 mg/dL     (Normal: 0.7-1.3)
BUN                     22 mg/dL      (Normal: 7-20) *** HIGH ***

HbA1c                   6.2 %         (Normal: <5.7) *** PRE-DIABETIC ***

---
*** MULTIPLE ABNORMAL VALUES - MEDICAL ATTENTION RECOMMENDED ***

Report generated by GutCheck Lab Systems
"""
    
    doc = fitz.open()
    page = doc.new_page()
    
    text_point = fitz.Point(50, 50)
    page.insert_text(text_point, content, fontsize=11, fontname="helv")
    
    doc.save("sample_reports/risk_55m.pdf")
    doc.close()
    print("Created: sample_reports/risk_55m.pdf")


if __name__ == "__main__":
    print("Generating sample blood test PDFs...")
    create_healthy_report()
    create_deficient_report()
    create_risk_report()
    print("\nAll sample reports created successfully!")
